### ISSUE TITLE
busybox depmod has different options than the full version

### ISSUE THREAD

**Issue by hh** [csc/Hanlon-Microkernel#18]
I just saw this in my build output: https://gist.github.com/hh/2c6bf30992dc133a41fb#file-build_hanlon_mk-out-L899

```
+ busybox depmod -a -b /home/hh/hanlon/Hanlon-Microkernel/tmp-build-dir/build_dir/tmp 3.8.13-tinycore
+ env LD_LIBRARY_PATH=/home/hh/hanlon/Hanlon-Microkernel/tmp-build-dir/build_dir/tmp/lib:/usr/lib/libfakeroot:/usr/lib64/libfakeroot:/usr/lib32/libfakeroot LD_PRELOAD= /home/hh/hanlon/Hanlon-Microkernel/tmp-build-dir/build_dir/tmp/lib/ld-linux.so.2 /home/hh/hanlon/Hanlon-Microkernel/tmp-build-dir/build_dir/tmp/bin/busybox depmod -a -b /home/hh/hanlon/Hanlon-Microkernel/tmp-build-dir/build_dir/tmp 3.8.13-tinycore
depmod: invalid option -- 'b'
```

It's part of rebuild_iso.sh: https://github.com/csc/Hanlon-Microkernel/blob/c5a734ac8ba25d43c9bda2f020d381c2ac46a719/iso-build-files/rebuild_iso.sh#L79

I'm not sure what we want, but here's the options:

# busybox version
root@mk002590E24CC2:/home/tc# depmod -h
depmod: invalid option -- 'h'
BusyBox v1.22.1 (2014-09-12 10:29:36 UTC) multi-call binary.

Usage: depmod [-qfwrsv] MODULE [symbol=value]...

        -r      Remove MODULE (stacks) or do autoclean
        -q      Quiet
        -v      Verbose
        -f      Force
        -w      Wait for unload
        -s      Report via syslog instead of stderr

# full version
[hh@b1 hanlon]$ depmod -h 
Usage:
        depmod -[aA] [options] [forced_version]

If no arguments (except options) are given, "depmod -a" is assumed

depmod will output a dependency list suitable for the modprobe utility.

Options:

        -a, --all            Probe all modules
        -A, --quick          Only does the work if there's a new module
        -e, --errsyms        Report not supplied symbols
        -n, --show           Write the dependency file on stdout only
        -P, --symbol-prefix  Architecture symbol prefix
        -C, --config=PATH    Read configuration from PATH
        -v, --verbose        Enable verbose mode
        -w, --warn           Warn on duplicates
        -V, --version        show version
        -h, --help           show this help

The following options are useful for people managing distributions:

        -b, --basedir=DIR    Use an image of a module tree.
        -F, --filesyms=FILE  Use the file instead of the
                             current kernel symbols.
        -E, --symvers=FILE   Use Module.symvers file to check
                             symbol versions.

**Comment by tjmcs** [comment]
With recent change to a Docker-based Microkernel image, this issue is no longer applicable (and will be closed)
