### ISSUE TITLE
Building-your-own-TCL-Extension documentation is outdated

### ISSUE THREAD

**Issue by hh** [csc/Hanlon-Microkernel#19]
On the wiki the setup for the build environment still look like it did over at Razor.
I'm thinking it's probably been updated.
I've racked my brain a bit today and can't seem to get all the necessary bits to compile kernel modules on tcl 5.x i386.

https://github.com/puppetlabs/Razor-Microkernel/wiki/Building-your-own-TCL-Extension#setting-up-your-build-environment

https://github.com/csc/Hanlon-Microkernel/wiki/Building-your-own-TCL-Extension#setting-up-your-build-environment

Where do these files come from?

```
tce-load -wi linux-headers-3.0.21-tinycore.tcz
tce-load -iw commoncpp2.tcz
```

Download http://tinycorelinux.net/5.x/x86/tcz/linux-headers-3.0.21-tinycore.tcz
wget: server returned error: HTTP/1.1 404 Not Found
Download http://tinycorelinux.net/5.x/x86/tcz/commoncpp2.tcz
wget: server returned error: HTTP/1.1 404 Not Found

**Comment by tjmcs** [comment]
With transition to a Docker-based Microkernel, this issue is no longer applicable (and will be closed)
