### ISSUE TITLE
Request cross compile microkernel for IA64 / Itanium & HP-UX

### ISSUE THREAD

**Issue by colineby** [csc/Hanlon-Microkernel#23]
Our project wants to bring support for our legacy platforms into a unified bare-metal management paradigm.  We have invested in a new generation of HP-UX systems. Could you please consider incorporating this as a new feature?

Colin Eby

**Comment by tjmcs** [comment]
With recent changes to support a Docker-based Microkernel (instead of the old TinyCore Linux based Microkernel) this issue is no longer applicable; closing...
